// Code generated by MockGen. DO NOT EDIT.
// Source: supplier.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/supplier.go -source=supplier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	supplier "github.com/ridwanakf/booking-orchestration-service/internal/supplier"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Book mocks base method.
func (m *MockClient) Book(ctx context.Context, req supplier.BookRequest) supplier.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Book", ctx, req)
	ret0, _ := ret[0].(supplier.Result)
	return ret0
}

// Book indicates an expected call of Book.
func (mr *MockClientMockRecorder) Book(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Book", reflect.TypeOf((*MockClient)(nil).Book), ctx, req)
}
