// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/repositories.go -source=repositories.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/ridwanakf/booking-orchestration-service/internal/model"
	repository "github.com/ridwanakf/booking-orchestration-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
	isgomock struct{}
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// AppendRefusal mocks base method.
func (m *MockBookingRepository) AppendRefusal(ctx context.Context, id uuid.UUID, e model.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendRefusal", ctx, id, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendRefusal indicates an expected call of AppendRefusal.
func (mr *MockBookingRepositoryMockRecorder) AppendRefusal(ctx, id, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendRefusal", reflect.TypeOf((*MockBookingRepository)(nil).AppendRefusal), ctx, id, e)
}

// Apply mocks base method.
func (m *MockBookingRepository) Apply(ctx context.Context, id uuid.UUID, t repository.Transition) (model.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, id, t)
	ret0, _ := ret[0].(model.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockBookingRepositoryMockRecorder) Apply(ctx, id, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockBookingRepository)(nil).Apply), ctx, id, t)
}

// Authorize mocks base method.
func (m *MockBookingRepository) Authorize(ctx context.Context, id uuid.UUID, maxAttempts int, supplierKey string, requestID *string) (int, model.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, id, maxAttempts, supplierKey, requestID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(model.Status)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Authorize indicates an expected call of Authorize.
func (mr *MockBookingRepositoryMockRecorder) Authorize(ctx, id, maxAttempts, supplierKey, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockBookingRepository)(nil).Authorize), ctx, id, maxAttempts, supplierKey, requestID)
}

// Events mocks base method.
func (m *MockBookingRepository) Events(ctx context.Context, id uuid.UUID) ([]model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", ctx, id)
	ret0, _ := ret[0].([]model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockBookingRepositoryMockRecorder) Events(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockBookingRepository)(nil).Events), ctx, id)
}

// FindPriorByFingerprint mocks base method.
func (m *MockBookingRepository) FindPriorByFingerprint(ctx context.Context, distributorID, fingerprint, excludeKey string, within time.Duration) (uuid.UUID, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPriorByFingerprint", ctx, distributorID, fingerprint, excludeKey, within)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPriorByFingerprint indicates an expected call of FindPriorByFingerprint.
func (mr *MockBookingRepositoryMockRecorder) FindPriorByFingerprint(ctx, distributorID, fingerprint, excludeKey, within any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPriorByFingerprint", reflect.TypeOf((*MockBookingRepository)(nil).FindPriorByFingerprint), ctx, distributorID, fingerprint, excludeKey, within)
}

// FindStale mocks base method.
func (m *MockBookingRepository) FindStale(ctx context.Context, t repository.StaleThresholds, limit int) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStale", ctx, t, limit)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStale indicates an expected call of FindStale.
func (mr *MockBookingRepositoryMockRecorder) FindStale(ctx, t, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStale", reflect.TypeOf((*MockBookingRepository)(nil).FindStale), ctx, t, limit)
}

// Flag mocks base method.
func (m *MockBookingRepository) Flag(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flag", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flag indicates an expected call of Flag.
func (mr *MockBookingRepositoryMockRecorder) Flag(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flag", reflect.TypeOf((*MockBookingRepository)(nil).Flag), ctx, id)
}

// GetByID mocks base method.
func (m *MockBookingRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBookingRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBookingRepository)(nil).GetByID), ctx, id)
}

// GetByKey mocks base method.
func (m *MockBookingRepository) GetByKey(ctx context.Context, distributorID, key string) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, distributorID, key)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockBookingRepositoryMockRecorder) GetByKey(ctx, distributorID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockBookingRepository)(nil).GetByKey), ctx, distributorID, key)
}

// InsertOrLoad mocks base method.
func (m *MockBookingRepository) InsertOrLoad(ctx context.Context, b model.Booking, requestID *string) (*model.Booking, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrLoad", ctx, b, requestID)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InsertOrLoad indicates an expected call of InsertOrLoad.
func (mr *MockBookingRepositoryMockRecorder) InsertOrLoad(ctx, b, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrLoad", reflect.TypeOf((*MockBookingRepository)(nil).InsertOrLoad), ctx, b, requestID)
}

// ParkIfUnknown mocks base method.
func (m *MockBookingRepository) ParkIfUnknown(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParkIfUnknown", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParkIfUnknown indicates an expected call of ParkIfUnknown.
func (mr *MockBookingRepositoryMockRecorder) ParkIfUnknown(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParkIfUnknown", reflect.TypeOf((*MockBookingRepository)(nil).ParkIfUnknown), ctx, id)
}

// ResolveStaleMarker mocks base method.
func (m *MockBookingRepository) ResolveStaleMarker(ctx context.Context, id uuid.UUID) (int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveStaleMarker", ctx, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResolveStaleMarker indicates an expected call of ResolveStaleMarker.
func (mr *MockBookingRepositoryMockRecorder) ResolveStaleMarker(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveStaleMarker", reflect.TypeOf((*MockBookingRepository)(nil).ResolveStaleMarker), ctx, id)
}
