// Code generated by MockGen. DO NOT EDIT.
// Source: orchestrator.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/orchestrator.go -source=orchestrator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOrchestrator is a mock of Orchestrator interface.
type MockOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockOrchestratorMockRecorder
	isgomock struct{}
}

// MockOrchestratorMockRecorder is the mock recorder for MockOrchestrator.
type MockOrchestratorMockRecorder struct {
	mock *MockOrchestrator
}

// NewMockOrchestrator creates a new mock instance.
func NewMockOrchestrator(ctrl *gomock.Controller) *MockOrchestrator {
	mock := &MockOrchestrator{ctrl: ctrl}
	mock.recorder = &MockOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrchestrator) EXPECT() *MockOrchestratorMockRecorder {
	return m.recorder
}

// SignalOutcome mocks base method.
func (m *MockOrchestrator) SignalOutcome(ctx context.Context, bookingID uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalOutcome", ctx, bookingID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignalOutcome indicates an expected call of SignalOutcome.
func (mr *MockOrchestratorMockRecorder) SignalOutcome(ctx, bookingID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalOutcome", reflect.TypeOf((*MockOrchestrator)(nil).SignalOutcome), ctx, bookingID, status)
}

// StartBooking mocks base method.
func (m *MockOrchestrator) StartBooking(ctx context.Context, bookingID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartBooking", ctx, bookingID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartBooking indicates an expected call of StartBooking.
func (mr *MockOrchestratorMockRecorder) StartBooking(ctx, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBooking", reflect.TypeOf((*MockOrchestrator)(nil).StartBooking), ctx, bookingID)
}
