// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/services.go -source=services.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/ridwanakf/booking-orchestration-service/internal/model"
	service "github.com/ridwanakf/booking-orchestration-service/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockBookingService is a mock of BookingService interface.
type MockBookingService struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceMockRecorder
	isgomock struct{}
}

// MockBookingServiceMockRecorder is the mock recorder for MockBookingService.
type MockBookingServiceMockRecorder struct {
	mock *MockBookingService
}

// NewMockBookingService creates a new mock instance.
func NewMockBookingService(ctrl *gomock.Controller) *MockBookingService {
	mock := &MockBookingService{ctrl: ctrl}
	mock.recorder = &MockBookingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingService) EXPECT() *MockBookingServiceMockRecorder {
	return m.recorder
}

// ApplyCallback mocks base method.
func (m *MockBookingService) ApplyCallback(ctx context.Context, id uuid.UUID, outcome service.SupplierOutcome) (service.CallbackResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCallback", ctx, id, outcome)
	ret0, _ := ret[0].(service.CallbackResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyCallback indicates an expected call of ApplyCallback.
func (mr *MockBookingServiceMockRecorder) ApplyCallback(ctx, id, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCallback", reflect.TypeOf((*MockBookingService)(nil).ApplyCallback), ctx, id, outcome)
}

// Create mocks base method.
func (m *MockBookingService) Create(ctx context.Context, req model.CreateRequest) (*model.Booking, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockBookingServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookingService)(nil).Create), ctx, req)
}

// Get mocks base method.
func (m *MockBookingService) Get(ctx context.Context, id uuid.UUID) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBookingServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBookingService)(nil).Get), ctx, id)
}
